# Directory Structure from __basedir
dir:
  logs: logs/

  output:
    base: dist/

    css: css/
    javascript: js/

    images: img/
    videos: img/

    fonts: css/
  
  assets:
    images: src/assets/images/
    videos: src/assets/videos/
    fonts: src/assets/fonts/
  
  preprocessed:
    scripts: src/scripts/
    styling: src/styles/
    pages: src/pages/

# Building options
video_options:
  scaling: 
    width: 1280
    height: 720
  poster: 
    generate: TRUE
    suffix: _poster

image_options:
  scaling:
    width: 1440
    height: 1280
  format: 
    filetype: jpeg
    extension: .jpg
    options: 
      quality: 90
      progressive: true

# Misc data, passed to every build process as variables
data: 
  ola: "Hallo Wurld!"

# Page structure
pages:
  static:
    -
      route: 'index'
      file: 'in_construction.pug'
      sitemap:
        canonical: ''
        priority: 0.8
        frequency: daily
    -
      route: '404'
      file: 'not_found.pug'
      sitemap: FALSE

# Other website files
cname: fold.com.br
robots:
  disallow: 
    - /404.html
  allow:
    - /